### PR TITLE
created Config.js,datgui use url from Config.js, module.js now warn if a table already exist, added jquery dependency :/

### PR DESCRIPTION
**Pull request by tuxun**
please review code :) datgui.js now use a newly created config.js file for load the url for the buttons of the gui

### CODE REVIEW

**Comment by tuxun** [comment]
i suggest merge and clean, please cause sure it need to be! https://github.com/CityScope/CS_cityscopeJS/issues/11

**Comment by RELNO** [comment]
@tuxun thanks for the contribution. A few things to note:
- I'd like to avoid AJAX and use native Fetch API. We've geared cityIO server API to allow Fetch [as we do in cityIO Frontend repo] 
- The Confing.js seems unnecessary if you converge the global URL var into `Storage.js`
- Is there a noticeable latency when calling cityIO table list?

**Comment by RELNO** [comment]
Also please pull latest before editing this PR, as modules.js has been updated

**Comment by tuxun** [comment]
Ajax is needed for the listing table function I imported from the frontend repo. I'm agree its a little lagish, and i didn't want to touch storage class cause all variables i saw in this class looked like related to table render.
I pulled just before make these two commit in a row, do you suggest i should have waited between both for being able to repull before the second commit? note: open for suggestion like "use fetch instead of ajax"=>i'll dig in it

**Comment by RELNO** [comment]
> I pulled just before make these two commit in a row

Prefect, wasn't sure if you did. 

> "use fetch instead of ajax"=>i'll dig in it

My bad -- the frontend still runs old code before we adapted cityIO to allow CORS and fetch API. See instead: https://github.com/CityScope/CS_CityScopeJS_Tables/blob/master/CSjs_MobCho/scripts/modules.js
for cleaner fetch example 

Storage can be amended, storing once the table URL there should not be an issue.

**Comment by tuxun** [comment]
so... i should `return` sort of ` fetch(Storage.cityIOtableURL).then promise` instead of `$_ajax`...
Is there a way you modify https://github.com/CityScope/CS_cityscopeJS/blob/master/js/UI/DATGUI.js to use storage.cityIOtableURL instead of hard coded url? doing so i would be ableto repost one pr only for the module.js/overwrite table test function instead of these two commits here.

**Pull request closed without merging**
